services:
  db:
    image: postgres
    container_name: rfid_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rfid_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_rfid:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: rfid_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data_rfid: