spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: rfid-backend
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_schema: public
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      client-type: lettuce
  flyway:
    enabled: true
    locations: classpath:db/migration,filesystem:/db/demo-migration

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui

epc:
  parser:
    strategy: test
