spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: rfid-backend
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:rfid_db}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_schema: public
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      client-type: lettuce
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/demo-migration

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui

epc:
  parser:
    strategy: default

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    kcz.rfid.backend: debug
