spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: rfid-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/rfid_db
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_schema: public
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: localhost
      client-type: lettuce
      port: 6379
  flyway:
    enabled: true
    locations: classpath:db/migration


server:
  port: 8080
