spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: rfid-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/rfid_db
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_schema: public
    hibernate:
      ddl-auto: update

server:
  port: 8080
